# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SynopsysDetectTask@8
  inputs:
    BlackDuckService: 'blackduck'
    DetectArguments: |
      --blackduck.trust.cert=true
      --detect.blackduck.signature.scanner.snippet.matching=FULL_SNIPPET_MATCHING
      --detect.blackduck.signature.scanner.individual.file.matching=ALL
      --detect.detector.search.depth=100
      --detect.blackduck.signature.scanner.upload.source.mode=true
      --detect.project.name=godot_test2
      --detect.project.version.name=Master
    DetectVersion: 'latest'